[test] test

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -49,10 +49,10 @@ jobs:
           git remote add mirror git@github.com:EpitechPromo2027/B-DEV-500-MPL-5-1-area-ewan.massonet.git
           
           echo "Fetching latest changes from mirror repository..."
-          git fetch mirror || { echo "Failed to fetch from mirror repository."; exit 1; }
+          git fetch || { echo "Failed to fetch from mirror repository."; exit 1; }
 
           echo "Merging changes from mirror repository..."
           git merge main --strategy-option theirs || { echo "Merge failed. Resolve conflicts and try again."; exit 1; }
 
           echo "Pushing to mirror repository..."
-          git push mirror HEAD:main || { echo "Push to mirror repository failed."; exit 1; }
+          git push HEAD:main || { echo "Push to mirror repository failed."; exit 1; }
